// src/lib/products/components.ts
import type { Product } from './types'

export const components: Product[] = [
  { slug: '80mm-universal-butt-joint-joining-plate-kit', name: '80mm Universal Butt Joint Joining Plate Kit', category: 'components', description: 'Universal butt joint plate kit for 80mm profiles.', imageUrl: '' },
  { slug: '40mm-3-way-corner-bracket-kit', name: '40mm 3-Way Corner Bracket Kit', category: 'components', description: 'Three-way corner bracket kit for 40mm profiles.', imageUrl: '' },
  { slug: '40mm-3-way-recessed-corner-bracket-kit-left', name: '40mm 3-Way Recessed Corner Bracket Kit - Left', category: 'components', description: 'Left-hand recessed 3-way corner bracket.', imageUrl: '' },
  { slug: '40mm-3-way-recessed-corner-bracket-kit-right', name: '40mm 3-Way Recessed Corner Bracket Kit - Right', category: 'components', description: 'Right-hand recessed 3-way corner bracket.', imageUrl: '' },
  { slug: '80mm-3-way-corner-bracket-kit', name: '80mm 3-Way Corner Bracket Kit', category: 'components', description: 'Three-way corner bracket kit for 80mm profiles.', imageUrl: '' },
  { slug: '80mm-3-way-recessed-corner-bracket-kit-left', name: '80mm 3-Way Recessed Corner Bracket Kit - Left', category: 'components', description: 'Left-hand recessed 3-way corner bracket for 80mm.', imageUrl: '' },
  { slug: '80mm-3-way-recessed-corner-bracket-kit-right', name: '80mm 3-Way Recessed Corner Bracket Kit - Right', category: 'components', description: 'Right-hand recessed 3-way corner bracket for 80mm.', imageUrl: '' },
  { slug: '80mm-90deg-3-way-corner-bracket-kit-left', name: '80mm 90° 3-Way Corner Bracket Kit - Left', category: 'components', description: 'Left-hand 90-degree 3-way corner bracket for 80mm.', imageUrl: '' },
  { slug: '80mm-90deg-3-way-corner-bracket-kit-right', name: '80mm 90° 3-Way Corner Bracket Kit - Right', category: 'components', description: 'Right-hand 90-degree 3-way corner bracket for 80mm.', imageUrl: '' },
  { slug: '40mm-sd-corner-bracket-kit', name: '40mm SD Corner Bracket Kit', category: 'components', description: 'Standard-duty corner bracket kit for 40mm profiles.', imageUrl: '' },
  { slug: '40mm-sd-panel-mount-corner-bracket-kit', name: '40mm SD Panel Mount Corner Bracket Kit', category: 'components', description: 'Standard-duty panel mount corner bracket for 40mm.', imageUrl: '' },
  { slug: '80mm-md-corner-bracket-kit', name: '80mm MD Corner Bracket Kit', category: 'components', description: 'Medium-duty corner bracket kit for 80mm profiles.', imageUrl: '' },
  { slug: '40mm-hd-corner-bracket-kit', name: '40mm HD Corner Bracket Kit', category: 'components', description: 'Heavy-duty corner bracket kit for 40mm profiles.', imageUrl: '' },
  { slug: '90deg-3x3-hole-joining-plate-kit', name: '90° 3x3 Hole Joining Plate Kit', category: 'components', description: '90-degree joining plate with 3x3 hole pattern.', imageUrl: '' },
  { slug: '40mm-sd-butt-joint-joining-plate', name: '40mm SD Butt Joint Joining Plate', category: 'components', description: 'Standard-duty butt joint plate for 40mm profiles.', imageUrl: '' },
  { slug: '40mm-hd-butt-joint-joining-plate-kit', name: '40mm HD Butt Joint Joining Plate Kit', category: 'components', description: 'Heavy-duty butt joint plate kit for 40mm profiles.', imageUrl: '' },
  { slug: '80mm-sd-butt-joint-joining-plate', name: '80mm SD Butt Joint Joining Plate', category: 'components', description: 'Standard-duty butt joint plate for 80mm profiles.', imageUrl: '' },
  { slug: '80mm-hd-butt-joint-joining-plate', name: '80mm HD Butt Joint Joining Plate', category: 'components', description: 'Heavy-duty butt joint plate for 80mm profiles.', imageUrl: '' },
  { slug: '40-6-standard-threaded-insert-kit', name: '40-6 Standard Threaded Insert Kit', category: 'components', description: 'Patented threaded insert kit for 40-6 slot profiles.', imageUrl: '' },
  { slug: '40-6-standard-double-threaded-insert-kit', name: '40-6 Standard Double Threaded Insert Kit', category: 'components', description: 'Double threaded insert kit for 40-6 slot profiles.', imageUrl: '' },
  { slug: '40-6-standard-threaded-insert-20deg-angle-kit', name: '40-6 Standard Threaded Insert - 20° Angle Kit', category: 'components', description: '20-degree angled threaded insert for 40-6 profiles.', imageUrl: '' },
  { slug: '40-6-standard-threaded-insert-kit-w-drop-in-nut-kit', name: '40-6 Standard Threaded Insert Kit W/ Drop-in Nut Kit', category: 'components', description: 'Threaded insert kit with drop-in nut included.', imageUrl: '' },
  { slug: '40-6-end-mount-threaded-insert', name: '40-6 End Mount Threaded Insert', category: 'components', description: 'End mount variant of the patented threaded insert.', imageUrl: '' },
  { slug: '40mm-sd-perpendicular-corner-bracket-kit', name: '40mm SD Perpendicular Corner Bracket Kit', category: 'components', description: 'Standard-duty perpendicular corner bracket for 40mm.', imageUrl: '' },
  { slug: '80mm-hd-perpendicular-bracket-kit', name: '80mm HD Perpendicular Bracket Kit', category: 'components', description: 'Heavy-duty perpendicular bracket for 80mm profiles.', imageUrl: '' },
  { slug: '80mm-hd-parallel-corner-bracket-kit', name: '80mm HD Parallel Corner Bracket Kit', category: 'components', description: 'Heavy-duty parallel corner bracket for 80mm profiles.', imageUrl: '' },
  { slug: '40mm-universal-perpendicular-bracket-kit', name: '40mm Universal Perpendicular Bracket Kit', category: 'components', description: 'Universal perpendicular bracket for 40mm profiles.', imageUrl: '' },
  { slug: '40mm-sd-universal-corner-bracket-kit', name: '40mm SD Universal Corner Bracket Kit', category: 'components', description: 'Standard-duty universal corner bracket for 40mm.', imageUrl: '' },
  { slug: '80mm-md-custom-universal-corner-bracket-kit', name: '80mm MD Custom Universal Corner Bracket Kit', category: 'components', description: 'Medium-duty custom universal corner bracket for 80mm.', imageUrl: '' },
  { slug: '40mm-end-mount-adjustable-angle-bracket-kit', name: '40mm End Mount Adjustable Angle Bracket Kit', category: 'components', description: 'Adjustable angle bracket with end mount configuration.', imageUrl: '' },
  { slug: '40mm-adjustable-angle-bracket-offset-profile-mount-kit', name: '40mm Adjustable Angle Bracket Offset Profile Mount Kit', category: 'components', description: 'Adjustable angle bracket with offset profile mount.', imageUrl: '' },
  { slug: '40mm-adjustable-angle-bracket-offset-profile-to-end-mount-kit', name: '40mm Adjustable Angle Bracket Offset Profile to End Mount Kit', category: 'components', description: 'Adjustable angle bracket from offset profile to end mount.', imageUrl: '' },
  { slug: '40mm-adjustable-angle-bracket-profile-to-end-mount-kit', name: '40mm Adjustable Angle Bracket Profile to End Mount Kit', category: 'components', description: 'Adjustable angle bracket from profile to end mount.', imageUrl: '' },
  { slug: '40mm-adjustable-angle-bracket-profile-offset-profile-mount-kit', name: '40mm Adjustable Angle Bracket Profile/Offset Profile Mount Kit', category: 'components', description: 'Adjustable angle bracket profile and offset profile mount.', imageUrl: '' },
  { slug: '40mm-adjustable-angle-plate-kit-left', name: '40mm Adjustable Angle Plate Kit - Left', category: 'components', description: 'Left-hand adjustable angle plate kit.', imageUrl: '' },
  { slug: '40mm-adjustable-angle-plate-kit-right', name: '40mm Adjustable Angle Plate Kit - Right', category: 'components', description: 'Right-hand adjustable angle plate kit.', imageUrl: '' },
  { slug: '27mm-angle-rivet-kit', name: 'Ø27mm Angle Rivet Kit', category: 'components', description: '27mm diameter angle rivet kit.', imageUrl: '' },
  { slug: '27x20mm-standard-rivet-kit', name: 'Ø27x20mm Standard Rivet Kit', category: 'components', description: '27x20mm standard rivet assembly kit.', imageUrl: '' },
  { slug: '27mm-25in-universal-angle-rivet-kit', name: 'Ø27mm .25in Universal Angle Rivet Kit', category: 'components', description: '27mm universal angle rivet kit, 0.25 inch.', imageUrl: '' },
  { slug: '27mm-375in-universal-angle-rivet-kit', name: 'Ø27mm .375in Universal Angle Rivet Kit', category: 'components', description: '27mm universal angle rivet kit, 0.375 inch.', imageUrl: '' },
  { slug: '40mm-compound-angle-bracket', name: '40mm Compound Angle Bracket', category: 'components', description: 'Compound angle bracket for complex joint configurations.', imageUrl: '' },
  { slug: '40mm-compound-angle-bracket-kit', name: '40mm Compound Angle Bracket Kit', category: 'components', description: 'Complete compound angle bracket kit for 40mm profiles.', imageUrl: '' },
  { slug: '75mm-2-hole-rivet-plate', name: '75mm 2-Hole Rivet Plate', category: 'components', description: '75mm flat rivet plate with 2-hole pattern.', imageUrl: '' },
  { slug: '150mm-2-hole-rivet-plate', name: '150mm 2-Hole Rivet Plate', category: 'components', description: '150mm flat rivet plate with 2-hole pattern.', imageUrl: '' },
  { slug: '300mm-2-hole-rivet-plate', name: '300mm 2-Hole Rivet Plate', category: 'components', description: '300mm flat rivet plate with 2-hole pattern.', imageUrl: '' },
  { slug: 'custom-2-hole-rivet-plates', name: 'Custom 2-Hole Rivet Plates', category: 'components', description: 'Custom length rivet plates — contact for sizing.', imageUrl: '' },
]
