// src/lib/products/doors-and-floors.ts
import type { Product } from './types'

export const doorsAndFloors: Product[] = [
  { slug: 'm16-stem-mt-leveling-foot-2700kg', name: 'M16 Stem Mt Leveling Foot (2700kg)', category: 'doors-and-floors', description: 'Heavy-duty leveling foot, M16 stem mount, 2700kg capacity.', imageUrl: '' },
  { slug: '70x70-m16-stem-caster-end-mount-kit', name: '70x70 M16 Stem Caster End Mount Kit', category: 'doors-and-floors', description: 'M16 stem caster end mounting kit for 70x70 profiles.', imageUrl: '' },
  { slug: '40mm-lh-inside-hinge-kit', name: '40mm LH Inside Hinge Kit', category: 'doors-and-floors', description: 'Left-hand interior hinge assembly for door frames.', imageUrl: '' },
  { slug: '40mm-rh-inside-hinge-kit', name: '40mm RH Inside Hinge Kit', category: 'doors-and-floors', description: 'Right-hand interior hinge assembly for door frames.', imageUrl: '' },
  { slug: '40mm-lh-outside-hinge-kit', name: '40mm LH Outside Hinge Kit', category: 'doors-and-floors', description: 'Left-hand exterior hinge assembly for door frames.', imageUrl: '' },
  { slug: '40mm-rh-outside-hinge-kit', name: '40mm RH Outside Hinge Kit', category: 'doors-and-floors', description: 'Right-hand exterior hinge assembly for door frames.', imageUrl: '' },
  { slug: '40mm-universal-panel-retainer-m8-straight-nut-black', name: '40mm Universal Panel Retainer w/M8 Straight Nut - Black', category: 'doors-and-floors', description: 'Panel fastening component with M8 straight nut, black.', imageUrl: '' },
  { slug: '40mm-universal-panel-retainer-m8-drop-in-t-stud-black', name: '40mm Universal Panel Retainer w/M8 Drop-In T-Stud - Black', category: 'doors-and-floors', description: 'Panel fastening with drop-in T-stud design, black.', imageUrl: '' },
  { slug: '40mm-panel-retainer-bracket-m6-straight-nut', name: '40mm Panel Retainer Bracket w/M6 Straight Nut', category: 'doors-and-floors', description: 'Bracket-style panel retainer with M6 straight nut.', imageUrl: '' },
  { slug: '40mm-panel-retainer-bracket-m6-drop-in-nut', name: '40mm Panel Retainer Bracket w/M6 Drop-In Nut', category: 'doors-and-floors', description: 'Panel retainer bracket with M6 drop-in nut.', imageUrl: '' },
  { slug: '40mm-panel-retainer-bracket-m6-drop-in-stud', name: '40mm Panel Retainer Bracket w/M6 Drop-In Stud', category: 'doors-and-floors', description: 'Panel retainer bracket with M6 drop-in stud.', imageUrl: '' },
  { slug: '40x80-m12-stem-plate-caster-mounting-kit', name: '40x80 M12 Stem/Plate Caster Mounting Kit', category: 'doors-and-floors', description: 'M12 stem/plate caster mounting for 40x80 profiles.', imageUrl: '' },
  { slug: '40x80-m16-stem-hd-plate-caster-profile-mounting-kit', name: '40x80 M16 Stem/HD Plate Caster Profile Mounting Kit', category: 'doors-and-floors', description: 'Heavy-duty M16 caster mounting for 40x80 profiles.', imageUrl: '' },
  { slug: '70x70-hd-floor-anchor-plate', name: '70x70 HD Floor Anchor Plate', category: 'doors-and-floors', description: 'Heavy-duty floor anchoring plate for 70x70 profiles.', imageUrl: '' },
  { slug: '70x70-m12-stem-caster-end-mounting-kit', name: '70x70 M12 Stem Caster End Mounting Kit', category: 'doors-and-floors', description: 'M12 stem caster end mount for 70x70 profiles.', imageUrl: '' },
  { slug: '70x70-m12-stem-plate-caster-end-mounting-kit', name: '70x70 M12 Stem/Plate Caster End Mounting Kit', category: 'doors-and-floors', description: 'Dual-mount M12 caster option for 70x70 profiles.', imageUrl: '' },
  { slug: '70x70-m16-stem-hd-plate-caster-end-mounting-kit', name: '70x70 M16 Stem/HD Plate Caster End Mounting Kit', category: 'doors-and-floors', description: 'Heavy-duty M16 caster mounting for 70x70 profiles.', imageUrl: '' },
  { slug: '80x80-m12-stem-plate-caster-mounting-kit', name: '80x80 M12 Stem/Plate Caster Mounting Kit', category: 'doors-and-floors', description: 'M12 caster mounting kit for 80x80 profiles.', imageUrl: '' },
  { slug: '80x80-m16-stem-hd-plate-caster-mounting-kit', name: '80x80 M16 Stem/HD Plate Caster Mounting Kit', category: 'doors-and-floors', description: 'Heavy-duty M16 caster mounting for 80x80 profiles.', imageUrl: '' },
  { slug: '40mm-floor-anchor-kit', name: '40mm Floor Anchor Kit', category: 'doors-and-floors', description: 'Basic floor anchoring assembly for 40mm profiles.', imageUrl: '' },
  { slug: '80mm-floor-anchor-bracket-kit', name: '80mm Floor Anchor Bracket Kit', category: 'doors-and-floors', description: 'Floor attachment brackets for 80mm components.', imageUrl: '' },
  { slug: '80mm-perpendicular-floor-anchor-bracket-kit', name: '80mm Perpendicular Floor Anchor Bracket Kit', category: 'doors-and-floors', description: 'Perpendicular floor anchoring for 80mm profiles.', imageUrl: '' },
  { slug: 'm8-stem-mount-leveling-foot-450kg', name: 'M8 Stem Mount Leveling Foot (450kg)', category: 'doors-and-floors', description: 'Lightweight leveling foot, M8, 450kg capacity.', imageUrl: '' },
  { slug: 'm8-stem-mt-leveling-foot-40mm-stud-1400kg', name: 'M8 Stem Mt Leveling Foot 40mm Stud (1400kg)', category: 'doors-and-floors', description: 'Enhanced leveling foot, M8, 40mm stud, 1400kg capacity.', imageUrl: '' },
  { slug: 'm12-stem-mount-leveling-foot-2000kg', name: 'M12 Stem Mount Leveling Foot (2000kg)', category: 'doors-and-floors', description: 'Mid-range leveling foot, M12, 2000kg capacity.', imageUrl: '' },
  { slug: 'm8-stem-mt-50mm-caster-w-total-brake-40kg', name: 'M8 Stem Mt 50mm Caster w/ Total Brake (40kg)', category: 'doors-and-floors', description: 'Small caster with locking brake, M8, 40kg capacity.', imageUrl: '' },
  { slug: 'm12-stem-mt-75mm-caster-w-total-brake-70kg', name: 'M12 Stem Mt 75mm Caster w/ Total Brake (70kg)', category: 'doors-and-floors', description: 'Medium caster with braking, M12, 70kg capacity.', imageUrl: '' },
  { slug: 'plate-mt-75mm-swivel-caster-w-total-brake-70kg', name: 'Plate Mt 75mm Swivel Caster w/ Total Brake (70kg)', category: 'doors-and-floors', description: 'Swiveling caster with brake, plate mount, 70kg.', imageUrl: '' },
  { slug: 'plate-mt-75mm-fixed-caster-70kg', name: 'Plate Mt 75mm Fixed Caster (70kg)', category: 'doors-and-floors', description: 'Non-swiveling 75mm plate-mount caster, 70kg.', imageUrl: '' },
  { slug: 'plate-mt-125mm-fixed-caster-125kg', name: 'Plate Mt 125mm Fixed Caster (125kg)', category: 'doors-and-floors', description: 'Fixed plate-mount caster for heavier loads, 125kg.', imageUrl: '' },
  { slug: 'plate-mt-125mm-swivel-caster-w-total-brake-125kg', name: 'Plate Mt 125mm Swivel Caster w/Total Brake (125kg)', category: 'doors-and-floors', description: 'Swivel caster with brake, plate mount, 125kg.', imageUrl: '' },
  { slug: 'm12-stem-mt-leveling-caster-black-250kg', name: 'M12 Stem Mt Leveling Caster - Black (250kg)', category: 'doors-and-floors', description: 'Caster combining mobility and leveling, M12, 250kg.', imageUrl: '' },
  { slug: 'plate-mt-swivel-leveling-caster-black-250kg', name: 'Plate Mt Swivel Leveling Caster - Black (250kg)', category: 'doors-and-floors', description: 'Swivel caster with leveling capability, 250kg.', imageUrl: '' },
  { slug: 'plate-mt-100mm-fixed-caster-400kg', name: 'Plate Mt 100mm Fixed Caster (400kg)', category: 'doors-and-floors', description: 'Heavy-duty fixed plate-mount caster, 400kg.', imageUrl: '' },
  { slug: 'plate-mt-100mm-swivel-caster-w-brake-400kg', name: 'Plate Mt 100mm Swivel Caster w/ Brake (400kg)', category: 'doors-and-floors', description: 'Swivel caster with brake for high-capacity use, 400kg.', imageUrl: '' },
  { slug: '40-6-hd-magnetic-locking-door-catch-kit', name: '40-6 HD Magnetic Locking Door Catch Kit', category: 'doors-and-floors', description: 'Heavy-duty magnetic door locking system.', imageUrl: '' },
  { slug: '40-6-magnetic-door-catch-kit', name: '40-6 Magnetic Door Catch Kit', category: 'doors-and-floors', description: 'Standard magnetic door locking assembly.', imageUrl: '' },
  { slug: '40-6-177mm-universal-handle-kit-black-caps', name: '40-6 177mm Universal Handle Kit - Black Caps', category: 'doors-and-floors', description: 'Door handle assembly with black caps, 177mm.', imageUrl: '' },
  { slug: '40-6-panel-gasket-slot-cover', name: '40-6 Panel Gasket/Slot Cover', category: 'doors-and-floors', description: 'Gasket and slot covering for panel edges.', imageUrl: '' },
  { slug: '40-6-snap-in-door-seal', name: '40-6 Snap-in Door Seal', category: 'doors-and-floors', description: 'Quick-fastening door seal component.', imageUrl: '' },
  { slug: '40-6-panel-gasket-1000mm', name: '40-6 Panel Gasket - 1000mm', category: 'doors-and-floors', description: 'Extended gasket strip for panel sealing, 1000mm.', imageUrl: '' },
  { slug: '40-6-snap-in-double-56mm-panel-retainer', name: '40-6 Snap-in Double 5.6mm Panel Retainer', category: 'doors-and-floors', description: 'Dual-panel retaining system, 5.6mm.', imageUrl: '' },
  { slug: '40-6-beveled-snap-in-56mm-panel-retainer', name: '40-6 Beveled Snap-in 5.6mm Panel Retainer', category: 'doors-and-floors', description: 'Angled snap-in panel retainer, 5.6mm.', imageUrl: '' },
  { slug: '40-6-snap-in-56mm-panel-retainer', name: '40-6 Snap-in 5.6mm Panel Retainer', category: 'doors-and-floors', description: 'Standard snap-in panel fastening, 5.6mm.', imageUrl: '' },
  { slug: '6mm-black-abs-textured-panel', name: '6mm Black ABS Textured Panel', category: 'doors-and-floors', description: 'Textured black ABS plastic panel material.', imageUrl: '' },
  { slug: '56mm-clear-polycarbonate-panel', name: '5.6mm Clear Polycarbonate Panel', category: 'doors-and-floors', description: 'Transparent polycarbonate panel for visibility.', imageUrl: '' },
  { slug: '56mm-black-pvc-coated-1in-wire-mesh', name: '5.6mm Black PVC-Coated 1" Wire Mesh', category: 'doors-and-floors', description: 'Black PVC-coated wire mesh panel material.', imageUrl: '' },
  { slug: '56mm-yellow-pvc-coated-1in-wire-mesh', name: '5.6mm Yellow PVC-Coated 1" Wire Mesh', category: 'doors-and-floors', description: 'Yellow safety mesh panel material.', imageUrl: '' },
  { slug: '0625in-grey-melamine-birch-plywood', name: '0.625" Grey Melamine Birch Plywood', category: 'doors-and-floors', description: 'Grey melamine birch plywood panel option.', imageUrl: '' },
  { slug: '40-6-bi-fold-door-guide-kit', name: '40-6 Bi-Fold Door Guide Kit', category: 'doors-and-floors', description: 'Bi-fold door tracking system.', imageUrl: '' },
  { slug: '40-6-bi-fold-door-support-pin-kit', name: '40-6 Bi-Fold Door Support Pin Kit', category: 'doors-and-floors', description: 'Support pins for bi-fold door operation.', imageUrl: '' },
]
