import type { Product } from './types'

export const hardware: Product[] = [
  { slug: 'm4x07-20mm-1-hole-offset-std-nut', name: 'M4x0.7 20mm 1-Hole Offset Std Nut', category: 'hardware', description: 'Offset standard nut, M4x0.7 thread, 20mm length.', imageUrl: '' },
  { slug: '1-4-20-20mm-1-hole-offset-std-nut', name: '1/4-20 20mm 1-Hole Offset Std Nut', category: 'hardware', description: 'Imperial thread standard offset nut, 1/4-20.', imageUrl: '' },
  { slug: 'm5x08-20mm-1-hole-std-offset-nut', name: 'M5x0.8 20mm 1-Hole Std Offset Nut', category: 'hardware', description: 'M5x0.8 offset nut variant, 20mm.', imageUrl: '' },
  { slug: 'm6x10-20mm-1-hole-std-offset-nut', name: 'M6x1.0 20mm 1-Hole Std Offset Nut', category: 'hardware', description: 'Single-hole offset nut, M6x1.0, 20mm.', imageUrl: '' },
  { slug: 'm6x10-39mm-2-hole-std-nut', name: 'M6x1.0 39mm 2-Hole Std Nut', category: 'hardware', description: 'Two-hole standard straight nut, M6x1.0, 39mm.', imageUrl: '' },
  { slug: 'm8x125-25mm-1-hole-std-offset-nut', name: 'M8x1.25 25mm 1-Hole Std Offset Nut', category: 'hardware', description: 'Larger diameter offset nut, M8x1.25.', imageUrl: '' },
  { slug: 'm6x10x25mm-109-drop-in-t-stud', name: 'M6x1.0x25mm 10.9 Drop-In T-Stud', category: 'hardware', description: 'Grade 10.9 T-stud drop-in assembly kit, M6x1.0x25mm.', imageUrl: '' },
  { slug: 'm6x10-109-drop-in-nut', name: 'M6x1.0 10.9 Drop-In Nut', category: 'hardware', description: 'Grade 10.9 drop-in nut kit, M6x1.0.', imageUrl: '' },
  { slug: 'm8x125x25mm-109-drop-in-t-stud', name: 'M8x1.25x25mm 10.9 Drop-In T-Stud', category: 'hardware', description: 'Larger T-stud assembly kit, M8x1.25x25mm grade 10.9.', imageUrl: '' },
  { slug: 'm6x10-25mm-1-hole-angle-nut', name: 'M6x1.0 25mm 1-Hole Angle Nut', category: 'hardware', description: 'AngleLock fastening system angle nut, 25mm single-hole.', imageUrl: '' },
  { slug: 'm6x10-38mm-1-hole-angle-nut', name: 'M6x1.0 38mm 1-Hole Angle Nut', category: 'hardware', description: 'Extended 1-hole angle nut, M6x1.0, 38mm.', imageUrl: '' },
  { slug: 'm6x10-38mm-2-hole-angle-nut', name: 'M6x1.0 38mm 2-Hole Angle Nut', category: 'hardware', description: 'Two-hole 38mm angle nut, M6x1.0.', imageUrl: '' },
  { slug: 'm6x10-44mm-2-hole-angle-nut', name: 'M6x1.0 44mm 2-Hole Angle Nut', category: 'hardware', description: 'Two-hole 44mm angle nut configuration.', imageUrl: '' },
  { slug: 'm6x10-60mm-2-hole-angle-nut', name: 'M6x1.0 60mm 2-Hole Angle Nut', category: 'hardware', description: 'Longer 2-hole angle nut, M6x1.0, 60mm.', imageUrl: '' },
  { slug: 'm6x10-79mm-2-hole-angle-nut', name: 'M6x1.0 79mm 2-Hole Angle Nut', category: 'hardware', description: 'Extended 2-hole angle nut variant, 79mm.', imageUrl: '' },
  { slug: 'm6x10-78mm-3-hole-angle-nut', name: 'M6x1.0 78mm 3-Hole Angle Nut', category: 'hardware', description: 'Three-hole configuration angle nut, 78mm.', imageUrl: '' },
  { slug: 'm6x10-100mm-3-hole-angle-nut', name: 'M6x1.0 100mm 3-Hole Angle Nut', category: 'hardware', description: 'Larger 3-hole angle nut, 100mm.', imageUrl: '' },
  { slug: '3-way-corner-bracket-washer-plate', name: '3-Way Corner Bracket Washer Plate', category: 'hardware', description: 'Washer plate assembly for 3-way corner brackets.', imageUrl: '' },
  { slug: '3-way-corner-bracket-plate-kit-50mm', name: '3-Way Corner Bracket Plate Kit 50mm SHCS', category: 'hardware', description: '50mm socket head cap screw bracket plate kit.', imageUrl: '' },
  { slug: '3-way-corner-bracket-plate-kit-55mm', name: '3-Way Corner Bracket Plate Kit 55mm SHCS', category: 'hardware', description: '55mm socket head cap screw bracket plate kit.', imageUrl: '' },
  { slug: '3-way-corner-bracket-plate-kit-65mm', name: '3-Way Corner Bracket Plate Kit 65mm SHCS', category: 'hardware', description: '65mm socket head cap screw bracket plate kit.', imageUrl: '' },
  { slug: 'm6-washer', name: 'M6 Washer', category: 'hardware', description: 'M6 metric washer, bright zinc plated.', imageUrl: '' },
  { slug: 'm8-washer', name: 'M8 Washer', category: 'hardware', description: 'M8 metric washer, bright zinc plated.', imageUrl: '' },
  { slug: 'm6x10-109-flange-nut', name: 'M6x1.0 10.9 Flange Nut', category: 'hardware', description: 'Grade 10.9 flanged nut, M6x1.0.', imageUrl: '' },
  { slug: 'm6x10-109-nylon-insert-flange-locknut', name: 'M6x1.0 10.9 Nylon-Insert Flange Locknut', category: 'hardware', description: 'Grade 10.9 flanged locknut with nylon insert.', imageUrl: '' },
  { slug: 'm8x125-109-flange-nut', name: 'M8x1.25 10.9 Flange Nut', category: 'hardware', description: 'Larger grade 10.9 flanged nut, M8x1.25.', imageUrl: '' },
  { slug: 'm6x10x20mm-129-flanged-shcs', name: 'M6x1.0x20mm 12.9 Flanged SHCS', category: 'hardware', description: 'Grade 12.9 flanged socket head cap screw, M6x1.0x20mm.', imageUrl: '' },
]
