// src/lib/products/motion.ts
import type { Product } from './types'

export const motion: Product[] = [
  { slug: '40mm-roller-bracket-kit', name: '40mm Roller Bracket Kit', category: 'motion', description: 'Enables smooth rolling motion for assemblies requiring component movement.', imageUrl: 'https://anglelock.com/hubfs/Products/Motion/40mm%20Roller%20Bracket%20Kit/40mm%20Roller%20Bracket%20Axo.png' },
  { slug: '40mm-pivot-bracket-offset-profile-mount-kit', name: '40mm Pivot Bracket Offset Profile Mount Kit', category: 'motion', description: 'Offset mount pivot bracket enabling angular rotation at profile intersections.', imageUrl: 'https://anglelock.com/hs-fs/hubfs/Products/Components/40mm%20Pivot%20Bracket%20Offset%20Profile%20Mount/Product%20Images/40mm%20Offset%20Profile%20Mount%20Pivot%20Bracket%20Kit%20Axo.png' },
  { slug: '40mm-pivot-bracket-profile-mount-to-end-mount-kit', name: '40mm Pivot Bracket Profile Mount to End Mount Kit', category: 'motion', description: 'Connects profile-side and end-side pivot points for articulating assemblies.', imageUrl: 'https://anglelock.com/hs-fs/hubfs/Products/Components/40mm%20Pivot%20Bracket%20Profile%20Mount%20to%20End%20Mount%20Kit/Product%20Images/40mm%20Pivot%20Brkt_Profile%20Mt%20to%20End%20Mt%20Axo.png' },
  { slug: '40mm-pivot-bracket-end-mount-kit', name: '40mm Pivot Bracket End Mount Kit', category: 'motion', description: 'End-mount pivot bracket for rotational adjustment at frame ends.', imageUrl: 'https://anglelock.com/hs-fs/hubfs/Products/Components/40mm%20Pivot%20Bracket%20End%20Mount%20Kit/Product%20Images/40mm%20Pivot%20Bracket_End%20Mount%20Kit%20Axo.png' },
  { slug: '40mm-pivot-bracket-offset-profile-to-end-mount-kit', name: '40mm Pivot Bracket Offset Profile to End Mount Kit', category: 'motion', description: 'Transitions an offset profile mount to an end mount with pivot capability.', imageUrl: 'https://anglelock.com/hubfs/3-1.webp' },
  { slug: '40mm-pivot-bracket-profile-to-offset-profile-mount-kit', name: '40mm Pivot Bracket Profile to Offset Profile Mount Kit', category: 'motion', description: 'Connects standard and offset profile mounts via a pivoting bracket.', imageUrl: 'https://anglelock.com/hs-fs/hubfs/Products/Components/40mm%20Pivot%20Bracket%20Profile%20to%20Offset%20Profile%20Mount%20Kit/Product%20Images/40mm%20Pivot%20Brkt_Profile%20Mt%20to%20Offset%20Profile%20Mt%20Axo.png' },
  { slug: '40mm-rh-inline-pivot-kit', name: '40mm RH Inline Pivot Kit', category: 'motion', description: 'Right-hand inline pivot assembly for door and panel applications.', imageUrl: 'https://anglelock.com/hs-fs/hubfs/Products/Components/40mm%20Rh%20Inline%20Pivot%20Kit/Product%20Images/40mm%20RH%20Inline%20Pivot%20Kit%20Axo.png' },
  { slug: '40mm-lh-inline-pivot-kit', name: '40mm LH Inline Pivot Kit', category: 'motion', description: 'Left-hand inline pivot assembly for door and panel applications.', imageUrl: 'https://anglelock.com/hs-fs/hubfs/Products/Components/40mm%20LH%20Inline%20Pivot%20Kit/Product%20Images/40mm%20LH%20Inline%20Pivot%20Kit%20Axo.png' },
  { slug: '40x40-sd-roller-carriage-kit-outside-mount', name: '40x40 SD Roller Carriage Kit - Outside Mount', category: 'motion', description: 'Standard-duty roller carriage for sliding door systems on 40x40 profiles.', imageUrl: 'https://anglelock.com/hubfs/40X40%20SD%20Roller%20Carriage%20Kit%2c%20Outside%20Mount_Axo.png' },
  { slug: '40x40-hd-roller-carriage-kit-outside-mount', name: '40x40 HD Roller Carriage Kit - Outside Mount', category: 'motion', description: 'Heavy-duty roller carriage for demanding sliding applications on 40x40 profiles.', imageUrl: 'https://anglelock.com/hubfs/Products/Motion/40x40%20HD%20Roller%20Carriage%20Kit,%20Outside%20Mount/Product%20Images/40x40%20HD%20Roller%20Carriage_Axo.png' },
  { slug: '40x80-sd-roller-carriage-kit-outside-mount', name: '40x80 SD Roller Carriage Kit - Outside Mount', category: 'motion', description: 'Standard-duty roller carriage for sliding systems on 40x80 profiles.', imageUrl: 'https://anglelock.com/hubfs/80mm%20SD%20Roller%20Carriage%20Kit_Axo.png' },
  { slug: '40x80-hd-roller-carriage-kit-outside-mount', name: '40x80 HD Roller Carriage Kit - Outside Mount', category: 'motion', description: 'Heavy-duty roller carriage for demanding sliding applications on 40x80 profiles.', imageUrl: 'https://anglelock.com/hubfs/Products/Motion/40x80%20HD%20Roller%20Carriage%20Kit,%20Outside%20Mount/Product%20Images/80mm%20HD%20Roller%20Carriage_Outside%20Mount_Axo.png' },
]
